Loading llm/pytorch/2.0.0
  Loading requirement: cuda/11.7.1 nccl/2.12.12-1-cuda cudnn/8.5.0.96-11.7-cuda
    gcc/8.5.0 openmpi/4.1.1-cuda intel-mkl/2020.4 magma/2.7.0-cuda sox/14.4.2
    sparsehash/2.0.3 libjpeg-turbo/2.1.3 pytorch-gpu/py3/2.0.0
[2023-09-15 16:04:09,505] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-15 16:04:09,523] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
zaerfdfgbdfgh
zaerfdfgbdfgh
{'deepspeed_config': {'deepspeed_config_file': 'configs/zero_stage2_config.json'}, 'downcast_bf16': 'no', 'fsdp_config': {}, 'main_training_function': 'main', 'megatron_lm_config': {}, 'mixed_precision': 'no', 'same_network': True, 'use_cpu': False, 'dynamo_backend': 'NO', 'machine_rank': 0, 'main_process_ip': 'r13i3n5', 'main_process_port': 25020, 'num_machines': 2, 'num_processes': 8, 'compute_environment': 'LOCAL_MACHINE', 'distributed_type': 'DEEPSPEED', 'rdzv_backend': 'c10d', 'gpu_ids': 'all', 'tpu_env': [], 'tpu_use_cluster': False, 'tpu_use_sudo': False}
{'deepspeed_config': {'deepspeed_config_file': 'configs/zero_stage2_config.json'}, 'downcast_bf16': 'no', 'fsdp_config': {}, 'main_training_function': 'main', 'megatron_lm_config': {}, 'mixed_precision': 'no', 'same_network': True, 'use_cpu': False, 'dynamo_backend': 'NO', 'machine_rank': 1, 'main_process_ip': 'r13i3n5', 'main_process_port': 25020, 'num_machines': 2, 'num_processes': 8, 'compute_environment': 'LOCAL_MACHINE', 'distributed_type': 'DEEPSPEED', 'rdzv_backend': 'c10d', 'gpu_ids': 'all', 'tpu_env': [], 'tpu_use_cluster': False, 'tpu_use_sudo': False}
[2023-09-15 16:04:27,580] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-15 16:04:28,189] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-15 16:04:31,945] [WARNING] [runner.py:196:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
Detected CUDA_VISIBLE_DEVICES=0,1,2,3 but ignoring it because one or several of --include/--exclude/--num_gpus/--num_nodes cl args were used. If you want to use CUDA_VISIBLE_DEVICES don't pass any of these arguments to deepspeed.
[2023-09-15 16:04:31,945] [INFO] [runner.py:555:main] cmd = /gpfslocalsup/pub/anaconda-py3/2023.03/envs/pytorch-gpu-2.0.0+py3.10.9/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMiwgM119 --master_addr=127.0.0.1 --master_port=25020 --no_local_rank --enable_each_rank_log=None train.py --lr 0.5
[2023-09-15 16:04:33,377] [WARNING] [runner.py:196:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
Detected CUDA_VISIBLE_DEVICES=0,1,2,3 but ignoring it because one or several of --include/--exclude/--num_gpus/--num_nodes cl args were used. If you want to use CUDA_VISIBLE_DEVICES don't pass any of these arguments to deepspeed.
[2023-09-15 16:04:33,378] [INFO] [runner.py:555:main] cmd = /gpfslocalsup/pub/anaconda-py3/2023.03/envs/pytorch-gpu-2.0.0+py3.10.9/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMiwgM119 --master_addr=127.0.0.1 --master_port=25020 --no_local_rank --enable_each_rank_log=None train.py --lr 0.5
[2023-09-15 16:04:33,807] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-15 16:04:35,324] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-15 16:04:38,005] [INFO] [launch.py:138:main] 0 NCCL_ROOT=/gpfslocalsup/spack_soft/nccl/2.12.12-1/gcc-8.5.0-ieeojypb7yvb5ivcmno4ualrg7n4wadr
[2023-09-15 16:04:38,006] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3]}
[2023-09-15 16:04:38,006] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=4, node_rank=0
[2023-09-15 16:04:38,006] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2, 3]})
[2023-09-15 16:04:38,006] [INFO] [launch.py:163:main] dist_world_size=4
[2023-09-15 16:04:38,006] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3
[2023-09-15 16:04:39,706] [INFO] [launch.py:138:main] 0 NCCL_ROOT=/gpfslocalsup/spack_soft/nccl/2.12.12-1/gcc-8.5.0-ieeojypb7yvb5ivcmno4ualrg7n4wadr
[2023-09-15 16:04:39,706] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3]}
[2023-09-15 16:04:39,706] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=4, node_rank=0
[2023-09-15 16:04:39,706] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2, 3]})
[2023-09-15 16:04:39,706] [INFO] [launch.py:163:main] dist_world_size=4
[2023-09-15 16:04:39,706] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3
[2023-09-15 16:04:42,138] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-15 16:04:42,139] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-15 16:04:42,141] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-15 16:04:42,196] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-15 16:04:43,944] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-15 16:04:44,087] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-15 16:04:44,089] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-15 16:04:44,133] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
Traceback (most recent call last):
  File "/gpfsdswork/projects/idris/sos/ssos029/idr_accelerate/examples/deepspeed/train.py", line 11, in <module>
  File "/gpfsdswork/projects/idris/sos/ssos029/idr_accelerate/examples/deepspeed/train.py", line 11, in <module>
Traceback (most recent call last):
    accelerator = Accelerator()
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/accelerator.py", line 279, in __init__
  File "/gpfsdswork/projects/idris/sos/ssos029/idr_accelerate/examples/deepspeed/train.py", line 11, in <module>
    accelerator = Accelerator()
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/accelerator.py", line 279, in __init__
Traceback (most recent call last):
  File "/gpfsdswork/projects/idris/sos/ssos029/idr_accelerate/examples/deepspeed/train.py", line 11, in <module>
    DeepSpeedPlugin() if os.environ.get("ACCELERATE_USE_DEEPSPEED", "false") == "true" else None
  File "<string>", line 14, in __init__
    DeepSpeedPlugin() if os.environ.get("ACCELERATE_USE_DEEPSPEED", "false") == "true" else None
  File "<string>", line 14, in __init__
    accelerator = Accelerator()
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/accelerator.py", line 279, in __init__
    accelerator = Accelerator()
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/accelerator.py", line 279, in __init__
    DeepSpeedPlugin() if os.environ.get("ACCELERATE_USE_DEEPSPEED", "false") == "true" else None
  File "<string>", line 14, in __init__
    DeepSpeedPlugin() if os.environ.get("ACCELERATE_USE_DEEPSPEED", "false") == "true" else None
  File "<string>", line 14, in __init__
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/utils/dataclasses.py", line 557, in __post_init__
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/utils/dataclasses.py", line 557, in __post_init__
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/utils/dataclasses.py", line 557, in __post_init__
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/utils/dataclasses.py", line 557, in __post_init__
    self._deepspeed_config_checks()
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/utils/dataclasses.py", line 742, in _deepspeed_config_checks
    self._deepspeed_config_checks()
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/utils/dataclasses.py", line 742, in _deepspeed_config_checks
    raise ValueError(
ValueError: When using `deepspeed_config_file`, the following accelerate config variables will be ignored: ['gradient_accumulation_steps', 'gradient_clipping', 'zero_stage', 'offload_optimizer_device', 'offload_param_device', 'offload_param_nvme_path', 'offload_optimizer_nvme_path', 'zero3_save_16bit_model', 'mixed_precision'].
Please specify them appropriately in the DeepSpeed config file.
If you are using an accelerate config file, remove others config variables mentioned in the above specified list.
The easiest method is to create a new config following the questionnaire via `accelerate config`.
It will only ask for the necessary config variables when using `deepspeed_config_file`.
    self._deepspeed_config_checks()
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/utils/dataclasses.py", line 742, in _deepspeed_config_checks
    self._deepspeed_config_checks()
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/utils/dataclasses.py", line 742, in _deepspeed_config_checks
    raise ValueError(
ValueError: When using `deepspeed_config_file`, the following accelerate config variables will be ignored: ['gradient_accumulation_steps', 'gradient_clipping', 'zero_stage', 'offload_optimizer_device', 'offload_param_device', 'offload_param_nvme_path', 'offload_optimizer_nvme_path', 'zero3_save_16bit_model', 'mixed_precision'].
Please specify them appropriately in the DeepSpeed config file.
If you are using an accelerate config file, remove others config variables mentioned in the above specified list.
The easiest method is to create a new config following the questionnaire via `accelerate config`.
It will only ask for the necessary config variables when using `deepspeed_config_file`.
    raise ValueError(
ValueError: When using `deepspeed_config_file`, the following accelerate config variables will be ignored: ['gradient_accumulation_steps', 'gradient_clipping', 'zero_stage', 'offload_optimizer_device', 'offload_param_device', 'offload_param_nvme_path', 'offload_optimizer_nvme_path', 'zero3_save_16bit_model', 'mixed_precision'].
Please specify them appropriately in the DeepSpeed config file.
If you are using an accelerate config file, remove others config variables mentioned in the above specified list.
The easiest method is to create a new config following the questionnaire via `accelerate config`.
It will only ask for the necessary config variables when using `deepspeed_config_file`.
    raise ValueError(
ValueError: When using `deepspeed_config_file`, the following accelerate config variables will be ignored: ['gradient_accumulation_steps', 'gradient_clipping', 'zero_stage', 'offload_optimizer_device', 'offload_param_device', 'offload_param_nvme_path', 'offload_optimizer_nvme_path', 'zero3_save_16bit_model', 'mixed_precision'].
Please specify them appropriately in the DeepSpeed config file.
If you are using an accelerate config file, remove others config variables mentioned in the above specified list.
The easiest method is to create a new config following the questionnaire via `accelerate config`.
It will only ask for the necessary config variables when using `deepspeed_config_file`.
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/gpfsdswork/projects/idris/sos/ssos029/idr_accelerate/examples/deepspeed/train.py", line 11, in <module>
  File "/gpfsdswork/projects/idris/sos/ssos029/idr_accelerate/examples/deepspeed/train.py", line 11, in <module>
  File "/gpfsdswork/projects/idris/sos/ssos029/idr_accelerate/examples/deepspeed/train.py", line 11, in <module>
  File "/gpfsdswork/projects/idris/sos/ssos029/idr_accelerate/examples/deepspeed/train.py", line 11, in <module>
    accelerator = Accelerator()    
accelerator = Accelerator()
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/accelerator.py", line 279, in __init__
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/accelerator.py", line 279, in __init__
    accelerator = Accelerator()
    accelerator = Accelerator()  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/accelerator.py", line 279, in __init__

  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/accelerator.py", line 279, in __init__
    DeepSpeedPlugin() if os.environ.get("ACCELERATE_USE_DEEPSPEED", "false") == "true" else None    
    DeepSpeedPlugin() if os.environ.get("ACCELERATE_USE_DEEPSPEED", "false") == "true" else None
DeepSpeedPlugin() if os.environ.get("ACCELERATE_USE_DEEPSPEED", "false") == "true" else None  File "<string>", line 14, in __init__
  File "<string>", line 14, in __init__

    DeepSpeedPlugin() if os.environ.get("ACCELERATE_USE_DEEPSPEED", "false") == "true" else None
  File "<string>", line 14, in __init__
  File "<string>", line 14, in __init__
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/utils/dataclasses.py", line 557, in __post_init__
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/utils/dataclasses.py", line 557, in __post_init__
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/utils/dataclasses.py", line 557, in __post_init__
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/utils/dataclasses.py", line 557, in __post_init__
    self._deepspeed_config_checks()
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/utils/dataclasses.py", line 742, in _deepspeed_config_checks
    self._deepspeed_config_checks()
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/utils/dataclasses.py", line 742, in _deepspeed_config_checks
        self._deepspeed_config_checks()self._deepspeed_config_checks()

  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/utils/dataclasses.py", line 742, in _deepspeed_config_checks
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/utils/dataclasses.py", line 742, in _deepspeed_config_checks
    raise ValueError(
ValueError:     When using `deepspeed_config_file`, the following accelerate config variables will be ignored: ['gradient_accumulation_steps', 'gradient_clipping', 'zero_stage', 'offload_optimizer_device', 'offload_param_device', 'offload_param_nvme_path', 'offload_optimizer_nvme_path', 'zero3_save_16bit_model', 'mixed_precision'].
Please specify them appropriately in the DeepSpeed config file.
If you are using an accelerate config file, remove others config variables mentioned in the above specified list.
The easiest method is to create a new config following the questionnaire via `accelerate config`.
It will only ask for the necessary config variables when using `deepspeed_config_file`.raise ValueError(

ValueError: When using `deepspeed_config_file`, the following accelerate config variables will be ignored: ['gradient_accumulation_steps', 'gradient_clipping', 'zero_stage', 'offload_optimizer_device', 'offload_param_device', 'offload_param_nvme_path', 'offload_optimizer_nvme_path', 'zero3_save_16bit_model', 'mixed_precision'].
Please specify them appropriately in the DeepSpeed config file.
If you are using an accelerate config file, remove others config variables mentioned in the above specified list.
The easiest method is to create a new config following the questionnaire via `accelerate config`.
It will only ask for the necessary config variables when using `deepspeed_config_file`.
    raise ValueError(    
raise ValueError(
ValueError: ValueErrorWhen using `deepspeed_config_file`, the following accelerate config variables will be ignored: ['gradient_accumulation_steps', 'gradient_clipping', 'zero_stage', 'offload_optimizer_device', 'offload_param_device', 'offload_param_nvme_path', 'offload_optimizer_nvme_path', 'zero3_save_16bit_model', 'mixed_precision'].
Please specify them appropriately in the DeepSpeed config file.
If you are using an accelerate config file, remove others config variables mentioned in the above specified list.
The easiest method is to create a new config following the questionnaire via `accelerate config`.
It will only ask for the necessary config variables when using `deepspeed_config_file`.: 
When using `deepspeed_config_file`, the following accelerate config variables will be ignored: ['gradient_accumulation_steps', 'gradient_clipping', 'zero_stage', 'offload_optimizer_device', 'offload_param_device', 'offload_param_nvme_path', 'offload_optimizer_nvme_path', 'zero3_save_16bit_model', 'mixed_precision'].
Please specify them appropriately in the DeepSpeed config file.
If you are using an accelerate config file, remove others config variables mentioned in the above specified list.
The easiest method is to create a new config following the questionnaire via `accelerate config`.
It will only ask for the necessary config variables when using `deepspeed_config_file`.
[2023-09-15 16:04:50,021] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 1577791
[2023-09-15 16:04:50,039] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 1577792
[2023-09-15 16:04:50,056] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 1577793
[2023-09-15 16:04:50,071] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 1577794
[2023-09-15 16:04:50,071] [ERROR] [launch.py:321:sigkill_handler] ['/gpfslocalsup/pub/anaconda-py3/2023.03/envs/pytorch-gpu-2.0.0+py3.10.9/bin/python', '-u', 'train.py', '--lr', '0.5'] exits with return code = 1
Traceback (most recent call last):
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/bin/idr_accelerate", line 8, in <module>
    sys.exit(run())
  File "/gpfsdswork/projects/idris/sos/ssos029/idr_accelerate/.local_accelerate/lib/python3.10/site-packages/idr_accelerate/launcher.py", line 120, in run
    launch_command(accelerate_args)
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 964, in launch_command
    deepspeed_launcher(args)
  File "/gpfslocalsup/src/pub/anaconda-py3/2023.03/llm-pytorch-2.0.0/local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 675, in deepspeed_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['deepspeed', '--no_local_rank', '--hostfile', 'None', '--launcher', 'pdsh', '--num_gpus', '4', '--master_port', '25020', 'train.py', '--lr', '0.5']' returned non-zero exit status 1.
[2023-09-15 16:04:51,722] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 1994861
[2023-09-15 16:04:51,723] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 1994862
[2023-09-15 16:04:51,742] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 1994863
[2023-09-15 16:04:51,758] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 1994864
[2023-09-15 16:04:51,773] [ERROR] [launch.py:321:sigkill_handler] ['/gpfslocalsup/pub/anaconda-py3/2023.03/envs/pytorch-gpu-2.0.0+py3.10.9/bin/python', '-u', 'train.py', '--lr', '0.5'] exits with return code = 1
srun: error: r13i3n5: task 0: Exited with exit code 1
srun: Terminating StepId=1955020.0
srun: error: r14i1n5: task 1: Terminated
srun: Force Terminated StepId=1955020.0
